### ISSUE TITLE
Add file timestamps to ArcAPI `/fs/dir/get`

### ISSUE THREAD

**Issue by IzKuipers** [IzK-ArcOS/ArcOS-API-Rewritten#1]
The idea here is quite simple. Add filesystem "Date Modified" (and maybe even "Date Created"?) to the ArcAPI response, specifically `/fs/dir/get`. The response for that endpoint would then be:
```json
{
    "valid": true,
    "data": {
        "name": ".",
        "scopedPath": ".",
        "files": [
            {
                "filename": "arcterm.conf",
                "scopedPath": "arcterm.conf",
                "size": 193,
                "mime": "application/json",
                "dateCreated": "2023-07-24T09:59:09.001Z", // <-- this
                "dateModified": "2023-07-24T09:59:09.001Z", // <-- this
            },

            . . .
        ],
        "directories": [
            . . .
        ]
    }
}
```

**Comment by nulqwy** [comment]
implemented as per 92152507108d6ddce3ab0715dab8d17aebe74bda with one nuance - on linux platforms `dateCreated` will actually contain last metadata modification date, instead of creation date
