### ISSUE TITLE
Template configuration options not `null`able

### ISSUE THREAD

**Issue by IzKuipers** [IzK-ArcOS/ArcOS-API-Rewritten#5]
According to the initial API design it should be possible for `Config.storage.template` to be set to `null` to completely disable templating, yet this doesn't happen on a freshly cloned instance of ArcAPI v2.

**Comment by nulqwy** [comment]
oh so i cant just tell dont fill template folder with anything to "disable" it...

**Comment by nulqwy** [comment]
should be implemented per 8cc372e8de4b46ac3000543f72fde14bee7cc827
