### ISSUE TITLE
[Linux/Python] venv creation needed

### ISSUE THREAD

**Issue by r1sk01** [IzK-ArcOS/ArcOS-API-Rewritten#7]
In order to use Linux with this, you need to create a Python venv to install pip packages.  
I have included the command before it as well, creating a venv and using it can be done by:  
cd ArcOS-API-Rewritten  
python -m venv venv  
source ./venv/bin/activate

**Comment by eversiege** [comment]
hey look @Spaceginner! First issue in years!

**Comment by nulqwy** [comment]
FINALLY

**Comment by nulqwy** [comment]
hm, this was kinda in a previous installation guide, i suppose @IzKuipers didn't include that in a new one

**Comment by nulqwy** [comment]
added instructions per 037fa24040aec2fdcdea2096af83df882ab0f532
